bugbakery/transcribee

- backend/transcribee_backend/settings/base.py
Otherwise we get CRSF errors with a user is both logged in via session auth and provides a token
> 🔧 Put token auth first

- worker/pdm.lock
- worker/pyproject.toml
The new upstream commit depends on the crates.io version of the automerge library. This should give us less trouble in the CI
> ⬆️ Bump automerge(fix ci?)

- .github/workflows/lint.yml
V2 uses node12, which GitHub deprecated and will be remove in september: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> ⬆️ Upgrade cache action to v3

- frontend/src/editor/transcription_editor.tsx
Fixes an issue where the debug bar was clipping to the top of the document while the editor state was loading
> 🐛 Move LazyDebugPanel out of blurred editor div

- worker/pdm.lock
- worker/pyproject.toml
- worker/run.py
watchfiles has much saner default, especially with filtering, debouncing, etc.
Furthermore, this is the same module used by uvicorn.
The old worker reloading is super broken, atleast on linux. It reloads in a infinite loop, as it catches all file open events.
> worker: Move from watchdog to watchfiles

- backend/openapi-schema.yml
- backend/scripts/create_worker.py
- backend/transcribee_backend/routers/document.py
- frontend/src/editor/player.tsx
- frontend/src/openapi-schema.ts
- proto/transcribee_proto/api.py
- worker/pdm.lock
- worker/pyproject.toml
- worker/run.py
- worker/transcribee_worker/config.py
- worker/transcribee_worker/reencode.py
- worker/transcribee_worker/worker.py
Reencode everything to 128k cbr mp3 and m4a
> ✨ Reencode task for worker

- backend/openapi-schema.yml
- backend/transcribee_backend/models/task.py
- frontend/src/editor/worker_status.tsx
- frontend/src/openapi-schema.ts
Reduces the size of the answer by the backend by about 10x, and doesn't loose any information.
We could even consider reducing the data transmitted even more.
> reduce information transmitted for list_tasks

- worker/transcribee_worker/api_client.py
- worker/transcribee_worker/document.py
If not receiving the messages a internal buffer of the `websockets` library fills up and it stops responding to the `ping` messages of the backend, which in turn closes the connection.
Closes #214 for me for now
> worker: discard unneeded websocket messages

- proto/transcribee_proto/document.py
Fixes a crash in the worker: If the align task was started after a speaker name was assigned, pydantic refused to parse the document
> 🐛 Fix type of document.speaker_names

- frontend/src/common/version.tsx
- frontend/src/common/virtual:git-version.d.ts
- frontend/vite.config.js
The previous approach contained some assumptions that don't always hold in production deployments:
- full git history checked out
- a remote exists
- this remote is named "origin"
> 🐛 Simplify version banner

- worker/transcribee_worker/worker.py
Otherwise the keepalive task wouldn't be run
> 🚑️ Run add_document_media_file in executor

- worker/transcribee_worker/identify_speakers.py
This fixes the frontend showing `Unnamed Speaker [object Object]` in documents with only one paragraph
> 🐛 Use automerge.Text in speaker id if only 1 para

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/editor/transcription_editor.tsx
Rendering just the text (so that searching and scrolling still kindof work) leads to better initial loading performance
> ⚡️ Only render children if in view 

- frontend/src/components/dropdown.tsx
- frontend/src/editor/transcription_editor.tsx
To be honest, I don't understand *why* this fixes it, but it does?
Fixes #316
> 🐛 Fix speaker buttons showing over speakerdropdown

- frontend/src/editor/editor_error_boundary.tsx
- frontend/src/editor/transcription_editor.tsx
We don't need a full rerender, we just clear the selection
https://github.com/ianstormtaylor/slate/pull/5407#issuecomment-1662449620
> ⚡️ Improve error handling performance

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/editor/automerge_websocket_editor.ts
- frontend/src/editor/slate_types.d.ts
> Basic undo functionality

- frontend/src/editor/transcription_editor.tsx
this makes performance a bit worse but usability a lot better
> fix loosing cursor position on new paragraph

- .gitignore
Following the instructions in the dev docs, `/.pnpm-store` gets a ton of files installed. Git dutifully and needlessly tries to scan for changes there, which is slow.
> Add /.pnpm-store to gitignore

- .devcontainer/Dockerfile
- .devcontainer/compose.yml
- .devcontainer/devcontainer.json
- doc/development_setup.md
This commit adds a dev container configuration file for a debian bullseye + nix container. Supporting IDEs, such as VS Code, should offer to open the cloned repository in the dev container, where users can then follow the [minimal setup](https://github.com/bugbakery/transcribee/blob/main/doc/development_setup.md#minimal-setup-nix) steps to quickly have a running dev instance without fiddling with their linux distro or nix locally.
It's a little bit more comfortable for VS Code users than the minimal docker setup.
> Add debian+nix dev container

- worker/transcribee_worker/torchaudio_align.py
> 🔧 Fix unpacking None value in alignment

- backend/openapi-schema.yml
- backend/transcribee_backend/auth.py
- backend/transcribee_backend/models/task.py
- backend/transcribee_backend/routers/document.py
- backend/transcribee_backend/routers/task.py
- backend/transcribee_backend/routers/user.py
- frontend/src/openapi-schema.ts
On my device with 12 documents, this brings down the load time from ~90ms to ~18ms and the number of queries performed for one request to `/api/v1/documents/` from 194 to 7
> ⚡️ Increase performance of list_documents by eager loading

- worker/tests/data/test_strict_sentence_paragraphs-doest_combine_long_para.json
- worker/tests/data/test_strict_sentence_paragraphs-leaves_special_paras.json
- worker/tests/test_transcribe.py
- worker/transcribee_worker/whisper_transcribe.py
- 🐛 Skip para recombination if produced para is > 30s
- 🐛 Fix DONT_COMBINE_RES not doing anything
> Paragraph recombination fixes

- frontend/src/editor/player.tsx
- frontend/src/editor/transcription_editor.tsx
- frontend/src/pages/document.tsx
- frontend/src/utils/use_audio.ts
- worker/transcribee_worker/config.py
- worker/transcribee_worker/reencode.py
- worker/transcribee_worker/worker.py
> ✨ Add basic video preview

- frontend/src/editor/export/webvtt.tsx
- frontend/src/utils/export_to_podlove.ts
Hi,
I add a new export option. The user can export the final transcript to a Podlove Publisher instance.
> feat(frontend) - Export to Podlove Publisher

- worker/generate_speaker_clusters.py
- worker/transcribee_worker/identify_speakers.py
This manually performs the speaker identification step and writes the speaker embeddings to a file. Can be used to debug speaker clustering / identification
> worker: add generate_speaker_clusters.py

- .github/workflows/lint.yml
- packaging/Procfile
- packaging/setup_backend.sh
- shell.nix
- 🧑‍💻 dev.sh: Wait for postgres before starting backend
- 🧑‍💻 Move redis database file to db folder
> Minor dev script improvements

- frontend/src/common/top_bar.tsx
- frontend/src/pages/document.tsx
> 💄 Sticky TopBar
