.dockerignore
dev.sh
doc/development_setup.md
frontend/vite.config.js
packaging/Dockerfile
packaging/dev_prepare.sh
worker/pdm.lock

The docker setup basically just calls the dev script in a nix shell

Add docker based dev-setup

---

backend/transcribee_backend/base/views.py
frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/editor/player.tsx
frontend/src/pages/document.tsx

♫ add playback bar

---

backend/pdm.lock
backend/pyproject.toml
shell.nix
worker/pdm.lock
worker/pyproject.toml

- 📦 add sqlalchemy[asyncio] worker dep explicitly
- 📦 nix: add hack to build native packages on mac
- 👷‍♀️ cache python dependencies in CI

👷‍♀️ fix ci build difference + fails

---

worker/pdm.lock
worker/pyproject.toml
worker/transcribee_worker/diarize.py

- 🐞 remove code needing pyannote.core.json
- 📦 add lightning-fabric dependency

📦 fix worker dependencies

---

worker/pdm.lock
worker/pyproject.toml

otherwise the worker will not start on linux systems without a cuda installation

use torch cpu version

---

frontend/src/components/popup.tsx
frontend/src/debugMode.tsx
frontend/src/editor/player.tsx
frontend/src/editor/transcription_editor.tsx
frontend/src/editor/types.ts
frontend/src/editor/worker_status.tsx
frontend/src/pages/document.tsx
frontend/src/utils/cssdom.tsx
frontend/src/utils/use_event.ts

- 📦 upgrade @automerge/automerge to ^2.0.3
- 📦 add automerge-wasm dependency
- ✨ highlight currently playing text
- 🐞 add missing react keys in worker_status.tsx
- ✨ seek audio when clicking on text

✨ Link transcript editor and player

---

CONTRIBUTING.md

📝 Fix link to dev setup document

---

packaging/Procfile
worker/pdm.lock
worker/pyproject.toml
worker/run.py

🧑‍💻 Reload worker if source code changed

---

frontend/src/pages/new_document.tsx

type="submit" is the default behaviour for buttons https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#type

🐛 Fix new doc form canceling on enter

---

frontend/src/editor/player.tsx

Float imprecisions make me saaaaad :(

🐛 Fuzzy-compare start time for highlighting

---

frontend/src/editor/transcription_editor.tsx

🚸 Set highlight if clicked outside of word

---

frontend/src/editor/player.tsx

- 💄 Center playbar, handle smaller screens
- 🐛 Resize waveform if viewport resized

💄 Center playbar (even on small screens) & resize waveform

---

frontend/src/utils/use_event.ts

useEvent: Fix registering cleanup function

---

frontend/src/components/button.tsx
frontend/src/editor/player.tsx
frontend/src/pages/user_home.tsx

- player: Center seek icons
- player: Adjust waveform style
- Fix unit of icon size

Small player style changes

---

backend/transcribee_backend/helpers/sync.py
backend/transcribee_backend/helpers/time.py
backend/transcribee_backend/routers/document.py
backend/transcribee_backend/routers/task.py

Order last recently changed documents first

---

frontend/src/components/form.tsx
frontend/src/editor/speaker_dropdown.tsx
frontend/src/editor/transcription_editor.tsx
frontend/src/editor/webvtt_export.tsx
frontend/src/utils/export/webvtt.ts

Code based on the identical feature in audapolis

✨ Add speaker names and word timings to webvtt export

---

frontend/src/components/tooltip.tsx
frontend/src/pages/document.tsx
frontend/src/utils/export/webvtt.ts

This seems to have been lost during rebasing of #162

🚸 Re-Add Tooltip if WebVTT export not possible

---

backend/scripts/set_password.py
backend/tests/test_performance.py
backend/transcribee_backend/auth.py

- 🔒️ Switch hashing to scrypt
- 🔒️ Use user_id instead of username in token
- 🔒️ Only accept tokens that are within valid perios
- ✨ Add script to set user password
Note: This breaks existing accounts, whose passwords need to be set again using the set_password.py script

Improve token auth

---

worker/run.py

⚰️ Remove duplicate definition of task_types

---

backend/pdm.lock
backend/pyproject.toml
frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/editor/debug_panel.tsx
frontend/src/editor/webvtt_export.tsx
frontend/src/editor/worker_status.tsx
frontend/src/utils/use_media_query.ts

- 🩹 Remove editable transcribee_proto from dev deps
- ➖ Replace react-responsive with custom useMediaQuery impl
- ⚡️ Cache SWR in local storage

Changes for beta deployment

---

frontend/src/editor/player.tsx
frontend/src/utils/button_hooks.ts

- Make player arrow buttons jump 2 seconds
- Enable seeking by holding player arrow buttons

Player seek buttons

---

backend/openapi-schema.yml
backend/transcribee_backend/models/task.py
frontend/src/openapi-schema.ts

The document is required by the worker to download the media

🚑️ Re-Add document to api task model

---

frontend/src/components/dropdown.tsx
frontend/src/components/modal.tsx
frontend/src/components/popup.tsx
frontend/src/editor/transcription_editor.tsx
frontend/src/utils/use_blur.ts
frontend/src/utils/use_on_click_outside.ts
frontend/src/utils/use_state_delayed.ts

- ❌ close popups when they use focus
- 💅 animate popups

✨ Popup improvements

---

backend/transcribee_backend/helpers/sync.py

Fixes #137
This is ~5x to 10x faster for a 20min podcast (~10 seconds to ~1 second)

backend: batch send initial automerge changes

---

worker/pdm.lock
worker/pyproject.toml

This crashes `pdm install --prod` otherwise

Remove editable proto from worker deps

---

worker/transcribee_worker/api_client.py

this fixes workering on long documents

🐞 set max_size=None in worker websocket

---

frontend/src/components/button.tsx
frontend/src/components/loading_spinner.tsx
frontend/src/pages/new_document.tsx

😵‍💫 Add loading spinner to new document modal

---

frontend/src/editor/transcription_editor.tsx

this slipped in somewhere but was never ready nor really working

🙈 remove half-finished word-highlight code

---

backend/openapi-schema.yml
backend/transcribee_backend/auth.py
backend/transcribee_backend/routers/document.py
backend/transcribee_backend/routers/task.py
frontend/src/api/document.ts
frontend/src/components/button.tsx
frontend/src/openapi-schema.ts
frontend/src/pages/document.tsx

allow document renaming

---

.github/workflows/docker.yml

💚 Add latest tag for main branch docker images

---

backend/openapi-schema.yml
backend/transcribee_backend/models/user.py
backend/transcribee_backend/routers/user.py
frontend/src/api/user.ts
frontend/src/common/top_bar.tsx
frontend/src/components/change_password.tsx
frontend/src/openapi-schema.ts

✨ Allow changing password

---

backend/data/models.json
backend/openapi-schema.yml
backend/tests/test_doc.py
backend/tests/test_performance.py
backend/transcribee_backend/config.py
backend/transcribee_backend/main.py
backend/transcribee_backend/routers/config.py
backend/transcribee_backend/routers/document.py
frontend/src/api/config.ts
frontend/src/openapi-schema.ts
frontend/src/pages/new_document.tsx
worker/scripts/generate_model_config.py

✨ Allow setting model / language on new doc page

---

backend/openapi-schema.yml
backend/transcribee_backend/helpers/tasks.py
backend/transcribee_backend/main.py
backend/transcribee_backend/routers/user.py
frontend/src/api/user.ts
frontend/src/common/top_bar.tsx
frontend/src/openapi-schema.ts
packaging/Dockerfile

Remove auth tokens from db on logout & after end of validity

---

README.md
doc/transcribee-logo.svg
frontend/index.html
frontend/package.json
frontend/pnpm-lock.yaml
frontend/vite.config.js

🐝 add logo & favicon

---

backend/transcribee_backend/routers/user.py
frontend/src/components/change_password.tsx

- 🐛 Change button text in password modal to 'Change Password'
- ✨ Logout user everywhere on pw change

✨ Logout user everywhere on pw change

---

frontend/src/pages/new_document.tsx

🐛 Fix default model and language

---

backend/data/models.json
worker/scripts/generate_model_config.py

🇬🇧 Show 'en' as language for english models

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/app.tsx
frontend/src/components/dropdown.tsx
frontend/src/editor/speaker_dropdown.tsx
frontend/src/editor/transcription_editor.tsx
frontend/src/index.css
frontend/src/utils/copy_text.ts

Replace grid layout with flexboxes and ditch sticky speaker names.

⚡️ Improve editor layout performance

---

worker/transcribee_worker/identify_speakers.py

- 🚸 Make automatic speaker names 1-indexed
- 🐛 Fix typings for worker callback

 🚸 Make automatic speaker names 1-indexed

---

backend/pyproject.toml
backend/transcribee_backend/helpers/sync.py

This is not a proper solution, but works for now.

🚑️ Add hotfix for websocket blocking the server

---

frontend/src/editor/editor_error_boundary.tsx
frontend/src/editor/transcription_editor.tsx

🐛 recover editor when our performance hacks break it

---

frontend/src/editor/transcription_editor.tsx

Fix speaker color div 🐝ing content editable

---

frontend/src/editor/transcription_editor.tsx

- Make loading spinner respect dark mode
- Render loading spinner in front of player

💄 Improve loading spinner styling

---

frontend/src/app.tsx

♻️ Rework auth in router

---

worker/tests/data/test_strict_sentence_paragraphs-protected_paragraphs.json
worker/transcribee_worker/whisper_transcribe.py

✨ Don't recombine paragraphs which only contain non-word text

---

backend/openapi-schema.yml
backend/transcribee_backend/config.py
frontend/src/app.tsx
frontend/src/openapi-schema.ts

this can be used to redirect to about.transcribee.net

logged out redirect

---

frontend/src/common/footer.tsx

✨ Add report bug link to footer

---

frontend/src/editor/export/index.tsx
frontend/src/editor/export/plaintext.tsx
frontend/src/utils/export/plaintext.ts

✨ Add plaintext export

---

backend/.gitignore
backend/openapi-schema.yml
backend/transcribee_backend/models/task.py
backend/transcribee_backend/routers/task.py
frontend/src/openapi-schema.ts

✨ Add task queue info endpoint

---

nix/pkgs/worker.nix

🚸 Set cargo home to tmp directory in worker nix derivation

---

frontend/src/common/footer.tsx
frontend/src/common/virtual:git-version.d.ts
frontend/vite.config.js
nix/pkgs/frontend.nix
shell.nix

- 🧹 Simplify version and allow to pass infos via env variables
- 🚸 Pass git infos in nix derivation

Simplify version and pass infos via nix derivation

---

nix/pkgs/frontend.nix

🐛 Configure npm to use temp dir in frontend nix derivation

---

frontend/pnpm-lock.yaml
nix/pkgs/frontend.nix

- 🐛 Fix cacerts for frontend derivation
- 🐛 Fix permission issues in frontend derivation

🐛 Fix frontend derivation

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/document.test.ts
frontend/src/document.ts
frontend/src/editor/automerge_websocket_editor.ts

🐛 Allow missing deps on loading initial document
